include(`foreach.m4')dnl
# Autogenerated by main.m4
#
# https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/globaltables_reqs_bestpractices.html

resource "aws_dynamodb_global_table" "default" {
  depends_on = [
foreach(`REGION', (REGIONS), `    aws_dynamodb_table.REGION,
')  ]

  # FIXME: Don't hardcode us-east-1!# 
  provider = aws.us-east-1

  name = var.name

  dynamic "replica" {
    for_each = toset(var.regions)

    content {
      region_name = replica.value
    }
  }
}
